name: 'Build application and deploy to Netlify'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build application'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run the tests
      run: npm test
    - name: Build
      run: npm run build
      env:  
        REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
    - uses: actions/upload-artifact@master
      with:
        name: webapp
        path: ./build

  deployNetflix:
    runs-on: ubuntu-latest
    name: 'Deploy to Netflix'
    needs: build
    steps:
    - uses: actions/checkout@v3
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - uses: actions/download-artifact@master
      with:
        name: webapp
        path: build/
    - uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: './build'
        production-branch: main
        enable-commit-comment: true
        fails-without-credentials: true
        github-token: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
        deploy-message: 'Published ${{ github.ref }}@${{ steps.commit.outputs.short }}'
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: '7bec95f8-348a-47e8-820c-f1635a4a7c77'

  deployAWS:
    runs-on: ubuntu-latest
    name: 'Deploy to AWS'
    needs: build
    steps:  
    - uses: actions/download-artifact@master
      with:
        name: webapp
        path: build/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Deploy
      run: aws s3 sync ./build s3://read-github-info-site