name: 'Build application and deploy to Netlify'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build application'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run the tests
      run: npm test
    - name: Build
      run: npm run build
      env:  
        REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }} 
    - uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: './build'
        production-branch: main
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: '7bec95f8-348a-47e8-820c-f1635a4a7c77'
        NETLIFY_DEPLOY_TO_PROD: true

